package context

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"
	"time"
)

const sectionHeader = "## Sentinel Context"
const sectionFooter = "<!-- end Sentinel Context -->"

// ContextService queries the graphify knowledge graph and injects
// relevant document context into a markdown file (typically AGENTS.md).
type ContextService struct {
	graphifyBinary string
	graphFile      string
}

// NewContextService creates a service with defaults.
func NewContextService() *ContextService {
	return &ContextService{
		graphifyBinary: "graphify",
		graphFile:      "graphify-out/graph.json",
	}
}

// QueryResult holds the output of a graphify query.
type QueryResult struct {
	RawOutput string
	Documents []string
	Concepts  []string
}

// Query runs graphify query with a 30s timeout and returns parsed results.
func (s *ContextService) Query(query string, budget int) (*QueryResult, error) {
	if _, err := os.Stat(s.graphFile); os.IsNotExist(err) {
		return nil, fmt.Errorf("context: graph not found at %s — run /graphify first", s.graphFile)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, s.graphifyBinary, "query", query, "--budget", fmt.Sprintf("%d", budget))
	cmd.Dir = "."
	output, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("context: graphify query failed: %w", err)
	}

	raw := string(output)
	return &QueryResult{
		RawOutput: raw,
		Documents: extractDocuments(raw),
		Concepts:  extractConcepts(raw),
	}, nil
}

func extractDocuments(raw string) []string {
	seen := make(map[string]bool)
	var docs []string

	for {
		start := strings.Index(raw, "[src=")
		if start == -1 {
			break
		}
		raw = raw[start+5:]

		end := strings.Index(raw, "]")
		if end == -1 {
			break
		}

		p := strings.TrimSpace(raw[:end])
		if !seen[p] {
			seen[p] = true
			docs = append(docs, p)
		}

		raw = raw[end+1:]
	}
	return docs
}

func extractConcepts(raw string) []string {
	seen := make(map[string]bool)
	var concepts []string

	for {
		start := strings.Index(raw, "NODE ")
		if start == -1 {
			break
		}
		raw = raw[start+5:]

		newlineEnd := strings.Index(raw, "\n")
		var line string
		if newlineEnd == -1 {
			line = raw
			raw = ""
		} else {
			line = raw[:newlineEnd]
			raw = raw[newlineEnd+1:]
		}

		bracketEnd := strings.Index(line, "[")

		var p string
		if bracketEnd == -1 {
			p = line
		} else {
			p = line[:bracketEnd]
		}

		c := strings.TrimSpace(p)
		if !seen[c] && len(c) > 3 {
			seen[c] = true
			concepts = append(concepts, c)
		}

		if raw == "" {
			break
		}
	}
	return concepts
}

// Format generates the markdown section to inject.
func Format(result *QueryResult, query string, limit int) string {
	var b strings.Builder
	b.WriteString(fmt.Sprintf("\n%s\n", sectionHeader))
	b.WriteString(fmt.Sprintf("> Generated by `sentinel context %q`\n\n", query))
	b.WriteString("### Relevant Documents\n")
	for i, doc := range result.Documents {
		if i >= limit {
			break
		}
		b.WriteString(fmt.Sprintf("- `%s`\n", doc))
	}
	if len(result.Documents) > limit {
		b.WriteString(fmt.Sprintf("- ... and %d more\n", len(result.Documents)-limit))
	}
	b.WriteString("\n### Key Concepts\n")
	for i, c := range result.Concepts {
		if i >= limit {
			break
		}
		b.WriteString(fmt.Sprintf("- %s\n", c))
	}
	b.WriteString(fmt.Sprintf("\n%s\n", sectionFooter))
	return b.String()
}

// Inject reads a markdown file, replaces or appends the Sentinel Context
// section, and writes it back.
func Inject(filePath, content string) error {
	data, err := os.ReadFile(filePath)
	if err != nil {
		if os.IsNotExist(err) {
			return os.WriteFile(filePath, []byte(content), 0644)
		}
		return fmt.Errorf("context: read %s: %w", filePath, err)
	}

	original := string(data)
	startIdx := strings.Index(original, sectionHeader)
	if startIdx >= 0 {
		endIdx := strings.Index(original[startIdx:], sectionFooter)
		if endIdx >= 0 {
			newContent := original[:startIdx] + content + original[startIdx+endIdx+len(sectionFooter):]
			return os.WriteFile(filePath, []byte(newContent), 0644)
		}
	}

	newContent := strings.TrimRight(original, "\n") + "\n" + content
	return os.WriteFile(filePath, []byte(newContent), 0644)
}
